### ISSUE TITLE
Wiring Schema

### ISSUE THREAD

**Issue by alnavasa** [kquinsland/ws3-to-esphome-bridge#2]
Hi, I am planning on building this same weather station, do you have a wiring schema? Thanks

**Comment by kquinsland** [comment]
Connect the transmit and receive pins on the WS3 to the pins you select for UART duty in the ESP Home config: https://github.com/kquinsland/ws3-to-esphome-bridge/blob/master/esphome/ws3.yaml#L83

Connect the ground pin of the ESP to the WS3 and supply 5V to the WS3 and you're done.
